### ISSUE TITLE
Error with mqjava.Responder

### ISSUE THREAD

**Issue by JanikBuecher** [ot4i/perf-harness#21]
We are getting following the error: 
```
Classpath: /usr/mqm/java/lib/*:/pkg/TIMBT/home/mqm/perfharness/jmstestp-master/perfharness.jar
LD_LIBRARY_PATH: :/usr/mqm/java/lib64
ControlThread1: START
ControlThread1: Fatal Error.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:83)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
        at [com.ibm.uk](http://com.ibm.uk/).hursley.perfharness.WorkerThread.newInstance(WorkerThread.java:529)
        at [com.ibm.uk](http://com.ibm.uk/).hursley.perfharness.ControlThread.addWorkers(ControlThread.java:834)
        at [com.ibm.uk](http://com.ibm.uk/).hursley.perfharness.ControlThread.setNumWorkers(ControlThread.java:514)
        at [com.ibm.uk](http://com.ibm.uk/).hursley.perfharness.ControlThread.run(ControlThread.java:249)
Caused by: [com.ibm.uk](http://com.ibm.uk/).hursley.perfharness.util.TypedPropertyException: Property [wo] not known.
        at [com.ibm.uk](http://com.ibm.uk/).hursley.perfharness.util.TypedProperties.getString(TypedProperties.java:155)
        at [com.ibm.uk](http://com.ibm.uk/).hursley.perfharness.util.TypedProperties.getInt(TypedProperties.java:178)
        at [com.ibm.uk](http://com.ibm.uk/).hursley.perfharness.mqjava.MQJavaWorkerThread.<init>(MQJavaWorkerThread.java:38)
        at [com.ibm.uk](http://com.ibm.uk/).hursley.perfharness.mqjava.Responder.<init>(Responder.java:53)
        ... 8 more
totalIterations=0,avgDuration=?,totalRate=0.00
ControlThread1: STOP
```
Reviewing the code it seems like mqjava.MQJavaWorkerThread need the -wo flag, but there is no default value set for this module and you cant provide it via commandline or config file

**Comment by pharrishur** [comment]
Hi, can you provide the command you executed that gave you this error please?

**Comment by stmassey** [comment]
It looks like Responder.properties was missing an entry. Ive added it, please update your file with the new version. We would probably advise you to use the JMS classes where possible, unless you are simulating a MQJava application.

**Comment by JanikBuecher** [comment]
Thank you!
